theme: minima
title: Youssix
description: Security Research - Low-level systems, virtualization, and reverse engineering
future: true
permalink: pretty

header_pages:
  - projects.md
  - writeups.md
  - about.md

minima:
  skin: dark
